server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          agape:
            client-id: agape
            client-secret: secret
            authorization_grant_type: password
            scope: read
            clientName: agape
        provider:
          agape:
            token-uri: http://${token_address}/oauth/token

logging:
  level:
    root: INFO

gateway:
  ribbon:
    eureka:
      enabled: false
    listOfServers: ${core_list}
    ServerListRefreshInterval: 15000