server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          agape:
            client-id: agape
            client-secret: secret
            authorization_grant_type: password
            scope: read
            clientName: agape
        provider:
          agape:
            token-uri: http://${TOKEN_ADDRESS:localhost:8090}/oauth/token
  cloud:
    loadbalancer:
      servers: ${CORE_LIST:localhost:8090}
      retry:
        max-retries-on-next-service-instance: 1
      health-check:
        interval: 15000

logging:
  level:
    root: INFO