server:
  port: 8090

spring:
  application:
    name: core
  datasource:
    url: jdbc:mariadb://${mariadb_address:localhost:3306}/agape?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${mariadb_username:root}
    password: ${mariadb_password:my366noy}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:${server_port}/.well-known/jwks.json

payment:
  kakaopay:
    host: https://kapi.kakao.com
    cancel-uri: http://localhost:${server_port}/payments/kakaoPayCancel
    success-uri: http://localhost:${server_port}/payments/kakaoPaySuccess
    success-fail-uri: http://localhost:${server_port}/payments/kakaoPaySuccessFail

logging:
  level:
    root: INFO
    org.springframework.security.oauth2: INFO